version: "3"
services:
  smoc4:
    build:
      context: .
      dockerfile: newclient/Dockerfile
    networks:
      - distributedWan
    hostname: smoc4
    environment:
      - CKPT_EXCHANGE_SMOC1=${SMOC1}
      - CKPT_EXCHANGE_SMOC2=${SMOC2}
      - CKPT_EXCHANGE_SMOC3=${SMOC3}
networks:
  distributedWan:
    external:
      name: loadbalancer_isolatedNetwork
