version: "3"
services:
  smoc1:
    build:
      context: .
      dockerfile: newclient/Dockerfile
    networks:
      - distributedWan
    hostname: ${HOSTNAME_SMOC1}
    tty: true
    stdin_open: true
    environment:
      - EVENT_EXCHANGE=${EVENT_EXCHANGE_FOR_SMOC1}
      - EVENT_QUEUE=${EVENT_QUEUE_FOR_SMOC1}
  smoc2:
    build:
      context: .
      dockerfile: newclient/Dockerfile
    networks:
      - distributedWan
    hostname: ${HOSTNAME_SMOC2}
    tty: true
    stdin_open: true
    environment:
      - EVENT_EXCHANGE=${EVENT_EXCHANGE_FOR_SMOC2}
      - EVENT_QUEUE=${EVENT_QUEUE_FOR_SMOC2}
  smoc3:
    build:
      context: .
      dockerfile: newclient/Dockerfile
    networks:
      - distributedWan
    hostname: ${HOSTNAME_SMOC3}
    tty: true
    stdin_open: true
    environment:
      - EVENT_EXCHANGE=${EVENT_EXCHANGE_FOR_SMOC3}
      - EVENT_QUEUE=${EVENT_QUEUE_FOR_SMOC3}
  smoc4:
    build:
      context: .
      dockerfile: newclient/Dockerfile
    networks:
      - distributedWan
    hostname: ${HOSTNAME_SMOC4}
    tty: true
    stdin_open: true
    environment:
      - EVENT_EXCHANGE=${EVENT_EXCHANGE_FOR_SMOC4}
      - EVENT_QUEUE=${EVENT_QUEUE_FOR_SMOC4}
networks:
  distributedWan:
    external:
      name: loadbalancer_isolatedNetwork
