version: "3"
services:
  smoc16:
    build:
      context: .
      dockerfile: newclient/Dockerfile
    networks:
      - distributedWan
    hostname: smoc16
    environment:
      - CKPT_EXCHANGE_SMOC1=${SMOC1}
      - CKPT_EXCHANGE_SMOC2=${SMOC2}
      - CKPT_EXCHANGE_SMOC3=${SMOC3}
      - CKPT_EXCHANGE_SMOC4=${SMOC4}
      - CKPT_EXCHANGE_SMOC5=${SMOC5}
      - CKPT_EXCHANGE_SMOC6=${SMOC6}
      - CKPT_EXCHANGE_SMOC7=${SMOC7}
      - CKPT_EXCHANGE_SMOC8=${SMOC8}
      - CKPT_EXCHANGE_SMOC9=${SMOC9}
      - CKPT_EXCHANGE_SMOC10=${SMOC10}
      - CKPT_EXCHANGE_SMOC11=${SMOC11}
      - CKPT_EXCHANGE_SMOC12=${SMOC12}
      - CKPT_EXCHANGE_SMOC13=${SMOC13}
      - CKPT_EXCHANGE_SMOC14=${SMOC14}
      - CKPT_EXCHANGE_SMOC15=${SMOC15}
networks:
  distributedWan:
    external:
      name: loadbalancer_isolatedNetwork
