version: "3"
services:
  smoc8:
    build:
      context: .
      dockerfile: newclient/Dockerfile
    networks:
      - distributedWan
    hostname: smoc8
    environment:
      - CKPT_EXCHANGE_SMOC1=${SMOC1}
      - CKPT_EXCHANGE_SMOC2=${SMOC2}
      - CKPT_EXCHANGE_SMOC3=${SMOC3}
      - CKPT_EXCHANGE_SMOC4=${SMOC4}
      - CKPT_EXCHANGE_SMOC5=${SMOC5}
      - CKPT_EXCHANGE_SMOC6=${SMOC6}
      - CKPT_EXCHANGE_SMOC7=${SMOC7}
networks:
  distributedWan:
    external:
      name: loadbalancer_isolatedNetwork
