version: "3"
services:
  smoc1:
    build:
      context: .
      dockerfile: newclient/Dockerfile
    networks:
      - distributedWan
    hostname: ${HOSTNAME_SMOC1}
    tty: true
    stdin_open: true
    environment:
      - EVENT_EXCHANGE=${EVENT_EXCHANGE_FOR_SMOC1}
      - EVENT_QUEUE=${EVENT_QUEUE_FOR_SMOC1}
      - EXCHANGE=${IPC_EXCHANGE_FOR_SMOC1}
      - QUEUE=${IPC_QUEUE_FOR_SMOC1}
      - EVENT_EXCHANGE_NEW=${EVENT_EXCHANGE_NEWCLIENT1}
      - EVENT_QUEUE_NEW=${EVENT_QUEUE_NEWCLIENT1}
      - CKPT_EXCHANGE_SMOC1=${IPC_EXCHANGE_FOR_SMOC1}
      - CKPT_EXCHANGE_SMOC2=${IPC_EXCHANGE_FOR_SMOC2}
      - CKPT_EXCHANGE_SMOC3=${IPC_EXCHANGE_FOR_SMOC3}
      - CKPT_EXCHANGE_SMOC4=${IPC_EXCHANGE_FOR_SMOC4}
      - CKPT_EXCHANGE_SMOC5=${IPC_EXCHANGE_FOR_SMOC5}
      - CKPT_EXCHANGE_SMOC6=${IPC_EXCHANGE_FOR_SMOC6}
      - CKPT_EXCHANGE_SMOC7=${IPC_EXCHANGE_FOR_SMOC7}
      - CKPT_EXCHANGE_SMOC8=${IPC_EXCHANGE_FOR_SMOC8}
      - CKPT_EXCHANGE_SMOC9=${IPC_EXCHANGE_FOR_SMOC9}
      - CKPT_EXCHANGE_SMOC10=${IPC_EXCHANGE_FOR_SMOC10}
      - CKPT_EXCHANGE_SMOC11=${IPC_EXCHANGE_FOR_SMOC11}
      - CKPT_EXCHANGE_SMOC12=${IPC_EXCHANGE_FOR_SMOC12}
      - CKPT_EXCHANGE_SMOC13=${IPC_EXCHANGE_FOR_SMOC13}
      - CKPT_EXCHANGE_SMOC14=${IPC_EXCHANGE_FOR_SMOC14}
      - CKPT_EXCHANGE_SMOC15=${IPC_EXCHANGE_FOR_SMOC15}
  smoc2:
    build:
      context: .
      dockerfile: newclient/Dockerfile
    networks:
      - distributedWan
    hostname: ${HOSTNAME_SMOC2}
    tty: true
    stdin_open: true
    environment:
      - EVENT_EXCHANGE=${EVENT_EXCHANGE_FOR_SMOC2}
      - EVENT_QUEUE=${EVENT_QUEUE_FOR_SMOC2}
      - EXCHANGE=${IPC_EXCHANGE_FOR_SMOC2}
      - QUEUE=${IPC_QUEUE_FOR_SMOC2}
      - CKPT_EXCHANGE_SMOC1=${IPC_EXCHANGE_FOR_SMOC1}
      - CKPT_EXCHANGE_SMOC2=${IPC_EXCHANGE_FOR_SMOC2}
      - CKPT_EXCHANGE_SMOC3=${IPC_EXCHANGE_FOR_SMOC3}
      - CKPT_EXCHANGE_SMOC4=${IPC_EXCHANGE_FOR_SMOC4}
      - CKPT_EXCHANGE_SMOC5=${IPC_EXCHANGE_FOR_SMOC5}
      - CKPT_EXCHANGE_SMOC6=${IPC_EXCHANGE_FOR_SMOC6}
      - CKPT_EXCHANGE_SMOC7=${IPC_EXCHANGE_FOR_SMOC7}
      - CKPT_EXCHANGE_SMOC8=${IPC_EXCHANGE_FOR_SMOC8}
      - CKPT_EXCHANGE_SMOC9=${IPC_EXCHANGE_FOR_SMOC9}
      - CKPT_EXCHANGE_SMOC10=${IPC_EXCHANGE_FOR_SMOC10}
      - CKPT_EXCHANGE_SMOC11=${IPC_EXCHANGE_FOR_SMOC11}
      - CKPT_EXCHANGE_SMOC12=${IPC_EXCHANGE_FOR_SMOC12}
      - CKPT_EXCHANGE_SMOC13=${IPC_EXCHANGE_FOR_SMOC13}
      - CKPT_EXCHANGE_SMOC14=${IPC_EXCHANGE_FOR_SMOC14}
      - CKPT_EXCHANGE_SMOC15=${IPC_EXCHANGE_FOR_SMOC15}
  smoc3:
    build:
      context: .
      dockerfile: newclient/Dockerfile
    networks:
      - distributedWan
    hostname: ${HOSTNAME_SMOC3}
    tty: true
    stdin_open: true
    environment:
      - EVENT_EXCHANGE=${EVENT_EXCHANGE_FOR_SMOC3}
      - EVENT_QUEUE=${EVENT_QUEUE_FOR_SMOC3}
      - EXCHANGE=${IPC_EXCHANGE_FOR_SMOC3}
      - QUEUE=${IPC_QUEUE_FOR_SMOC3}
      - CKPT_EXCHANGE_SMOC1=${IPC_EXCHANGE_FOR_SMOC1}
      - CKPT_EXCHANGE_SMOC2=${IPC_EXCHANGE_FOR_SMOC2}
      - CKPT_EXCHANGE_SMOC3=${IPC_EXCHANGE_FOR_SMOC3}
      - CKPT_EXCHANGE_SMOC4=${IPC_EXCHANGE_FOR_SMOC4}
      - CKPT_EXCHANGE_SMOC5=${IPC_EXCHANGE_FOR_SMOC5}
      - CKPT_EXCHANGE_SMOC6=${IPC_EXCHANGE_FOR_SMOC6}
      - CKPT_EXCHANGE_SMOC7=${IPC_EXCHANGE_FOR_SMOC7}
      - CKPT_EXCHANGE_SMOC8=${IPC_EXCHANGE_FOR_SMOC8}
      - CKPT_EXCHANGE_SMOC9=${IPC_EXCHANGE_FOR_SMOC9}
      - CKPT_EXCHANGE_SMOC10=${IPC_EXCHANGE_FOR_SMOC10}
      - CKPT_EXCHANGE_SMOC11=${IPC_EXCHANGE_FOR_SMOC11}
      - CKPT_EXCHANGE_SMOC12=${IPC_EXCHANGE_FOR_SMOC12}
      - CKPT_EXCHANGE_SMOC13=${IPC_EXCHANGE_FOR_SMOC13}
      - CKPT_EXCHANGE_SMOC14=${IPC_EXCHANGE_FOR_SMOC14}
      - CKPT_EXCHANGE_SMOC15=${IPC_EXCHANGE_FOR_SMOC15}
  smoc4:
    build:
      context: .
      dockerfile: newclient/Dockerfile
    networks:
      - distributedWan
    hostname: ${HOSTNAME_SMOC4}
    tty: true
    stdin_open: true
    environment:
      - EVENT_EXCHANGE=${EVENT_EXCHANGE_FOR_SMOC4}
      - EVENT_QUEUE=${EVENT_QUEUE_FOR_SMOC4}
      - EXCHANGE=${IPC_EXCHANGE_FOR_SMOC4}
      - QUEUE=${IPC_QUEUE_FOR_SMOC4}
      - CKPT_EXCHANGE_SMOC1=${IPC_EXCHANGE_FOR_SMOC1}
      - CKPT_EXCHANGE_SMOC2=${IPC_EXCHANGE_FOR_SMOC2}
      - CKPT_EXCHANGE_SMOC3=${IPC_EXCHANGE_FOR_SMOC3}
      - CKPT_EXCHANGE_SMOC4=${IPC_EXCHANGE_FOR_SMOC4}
      - CKPT_EXCHANGE_SMOC5=${IPC_EXCHANGE_FOR_SMOC5}
      - CKPT_EXCHANGE_SMOC6=${IPC_EXCHANGE_FOR_SMOC6}
      - CKPT_EXCHANGE_SMOC7=${IPC_EXCHANGE_FOR_SMOC7}
      - CKPT_EXCHANGE_SMOC8=${IPC_EXCHANGE_FOR_SMOC8}
      - CKPT_EXCHANGE_SMOC9=${IPC_EXCHANGE_FOR_SMOC9}
      - CKPT_EXCHANGE_SMOC10=${IPC_EXCHANGE_FOR_SMOC10}
      - CKPT_EXCHANGE_SMOC11=${IPC_EXCHANGE_FOR_SMOC11}
      - CKPT_EXCHANGE_SMOC12=${IPC_EXCHANGE_FOR_SMOC12}
      - CKPT_EXCHANGE_SMOC13=${IPC_EXCHANGE_FOR_SMOC13}
      - CKPT_EXCHANGE_SMOC14=${IPC_EXCHANGE_FOR_SMOC14}
      - CKPT_EXCHANGE_SMOC15=${IPC_EXCHANGE_FOR_SMOC15}
networks:
  distributedWan:
    external:
      name: loadbalancer_isolatedNetwork
